### ISSUE TITLE
Pyroscope can't use PVC 

### ISSUE THREAD

**Issue by tuananh2508** [pyroscope-io/helm-chart#13]
# Step to reproduce

1. Install Pyroscope using Helm
```
helm repo add pyroscope-io https://pyroscope-io.github.io/helm-chart
helm pull pyroscope-io/pyroscope 
tar -zxvf pyroscope-*
```

2. Edit `values.yaml` file
Set `persistent.enabled` to `true`

# Problem
```
$ kubectl get po -n monitoring
NAME                              READY   STATUS             RESTARTS   AGE
pyro-pyroscope-5f76c87778-zhmx6   0/1     CrashLoopBackOff   6          7m42s
$ kubectl logs -n monitoring pyro-pyroscope-5f76c87778-zhmx6
Error: could not initialize server: new storage: mkdir /var/lib/pyroscope/main: permission denied
```

I think this is because pyroscope pod run as non-root ?

**Comment by kolesnikovae** [comment]
Thank you for filing the issue @tuananh2508. Indeed, use of PVC in pyroscope helm chart could be more convenient. And there is already [a similar issue](https://github.com/pyroscope-io/pyroscope/issues/350). As a workaround, you could try to set pod security context `fsGroup` to `101` so that it matches user ID in the official docker image: https://github.com/pyroscope-io/helm-chart/pull/8.

What would you say if we had an `initContainer` that changes ownership of the mounted fs?

**Comment by tuananh2508** [comment]
Thanks for fast reply. This is what showing after using `fsgroup=100`

- Edit the  `values.yaml` file:
```
...
podSecurityContext:
      fsGroup: 101
....
```

- Use Helm to upgrade `helm upgrade --install ....`
```
$ kubectl get po -n monitoring
NAME                              READY   STATUS             RESTARTS   AGE
pyro-pyroscope-7b8f689bf5-h5wl7   0/1     CrashLoopBackOff   4          3m19s

$ kubectl describe po -n monitoring pyro-pyroscope-7b8f689bf5-h5wl7
...
Normal   Created    2m28s (x4 over 3m24s)   kubelet            Created container pyroscope
Normal   Started    2m27s (x4 over 3m24s)   kubelet            Started container pyroscope
Warning  BackOff    2m24s (x10 over 3m22s)  kubelet            Back-off restarting failed container

$ kubectl logs -n monitoring pyro-pyroscope-7b8f689bf5-h5wl7
Error: could not initialize server: new storage: Cannot write pid file "/var/lib/pyroscope/main/LOCK": open /var/lib/pyroscope/main/LOCK: permission denied
```

*Workaround*
Use `podSecurityContext.runAsUser=0`

**Comment by kolesnikovae** [comment]
Hm, interesting. Setting `fsGroup` to `101` should actually solve the problem - just have tested (v1.20, AWS EKS + EBS CSI driver). Could you please clarify kubernetes version and PVC provisioner used?

**Comment by tuananh2508** [comment]
Confirmed. You guy can fix by changing `fsGroup` to `101`.  Previously It was PVC provisioner problem. 
Still, Init Container would be more convinient :D. Thank you for helping !
