### ISSUE TITLE
Add renovate to update the image version

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/helm-chart#16]
Would be nice to have [renovate](https://docs.renovatebot.com/modules/manager/helm-values/) running against this repository, so that it updates the image automatically.

There are 2 levels for this implementation in my mind

- [x] Open up the PR, but we still merge manually
- [x] Open the PR and merge automatically

**Comment by kolesnikovae** [comment]
I see no reasons to merge such PRs manually. I'd go for the second option.
